name       : cryptsetup
version    : 2.2.2
release    : 9
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.2/cryptsetup-2.2.2.tar.xz : 2af0ec9551ab9c870074cae9d3f68d82cab004f4095fa89db0e4413713424a46
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module. These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format. Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - libgcrypt-devel
rundeps    :
    - devel: json-c-devel
optimize   :
    - size
    - lto
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
