name       : cryptsetup
version    : 2.3.3
release    : 10
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.3/cryptsetup-2.3.3.tar.xz : 3bca4ffe39e2f94cef50f6ea65acb873a6dbce5db34fc6bcefe38b6d095e82df
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module. These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format. Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - libgcrypt-devel
rundeps    :
    - devel : json-c-devel
optimize   :
    - size
    - lto
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
