name       : cryptsetup
version    : 2.6.1
release    : 16
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.6/cryptsetup-2.6.1.tar.xz : 410ded65a1072ab9c8e41added37b9729c087fef4d2db02bb4ef529ad6da4693
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module. These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format. Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - asciidoctor
    - pkgconfig(devmapper)
    - pkgconfig(json-c)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - libgcrypt-devel
rundeps    :
    - devel : json-c-devel
optimize   :
    - size
    - lto
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --disable-ssh-token \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
