name       : cryptsetup
version    : 1.7.5
release    : 8
source     :
    - https://www.kernel.org/pub/linux/utils/cryptsetup/v1.7/cryptsetup-1.7.5.tar.xz : 2b30cd1d0dd606a53ac77b406e1d37798d4b0762fa89de6ea546201906a251bd
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : system.base
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module. These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format. Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - libgcrypt-devel
optimize   :
    - size
    - lto
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
