name       : cryptsetup
version    : 1.7.0
release    : 2
source     :
    - https://www.kernel.org/pub/linux/utils/cryptsetup/v1.7/cryptsetup-1.7.0.tar.xz : 075524a7cc0db36d12119fa79116750accb1c6c8825d5faa2534b74b8ce3d148
license    :
    - LGPL-3.0
    - GPL-2.0
summary    : Utility to setup disk encryption using DMCrypt
description: |
    Cryptsetup is utility used to conveniently setup disk encryption based on DMCrypt kernel module.
    These include plain dm-crypt volumes, LUKS volumes, loop-AES and TrueCrypt (including VeraCrypt extension) format.
    Project also includes veritysetup utility used to conveniently setup DMVerity block integrity checking kernel module.
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(nss)
    - pkgconfig(devmapper)
setup      : |
    %configure --disable-static \
               --disable-pwquality \
               --disable-rpath \
               --disable-selinux \
               --enable-udev \
               --enable-cryptsetup-reencrypt \
               --enable-largefile
build      : |
    %make
install    : |
    %make_install
